src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use DateTimeInterface;


#[ORM\Entity(repositoryClass: PostsRepository::class)]
class Posts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

	#[ORM\Column(type: 'datetime')]
	private ?DateTimeInterface $datePublication = null;
	
    #[ORM\ManyToOne(inversedBy: 'UserPost')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $created_id = null;

    #[ORM\OneToMany(mappedBy: 'post_id', targetEntity: Comments::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Collection $CommentPost;

    public function __construct()
    {
        $this->datePublication = new \DateTime();
        $this->CommentPost = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }
	 public function getDatePublication(): ?DateTimeInterface
    {
        return $this->datePublication;
    }

    public function setDatePublication(?DateTimeInterface $datePublication): self
    {
        $this->datePublication = $datePublication;

        return $this;
    }

    public function getCreated_Id(): ?User
    {
        return $this->created_id;
    }

    public function setCreated_Id(?User $created_id): self
    {
        $this->created_id = $created_id;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->CommentPost;
    }

    public function addCommentPost(Comments $commentPost): self
    {
        if (!$this->CommentPost->contains($commentPost)) {
            $this->CommentPost->add($commentPost);
            $commentPost->setPostId($this);
        }

        return $this;
    }

    public function removeCommentPost(Comments $commentPost): self
    {
        if ($this->CommentPost->removeElement($commentPost)) {
            // set the owning side to null (unless already changed)
            if ($commentPost->getPostId() === $this) {
                $commentPost->setPostId(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\Entity\Posts;
use App\Form\CommentType;
use App\Form\PostType;
use App\Entity\Comments;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;


class ForumController extends AbstractController
{
    #[Route('/forum/{id}', name: 'app_forumpost')]
	 public function index(EntityManagerInterface $entityManager, int $id): Response
    {
        $post = $entityManager->getRepository(Posts::class)->findBy(['id' => $id], []);
     
	 //On met le $post[0] à null, comme ça le twig peut handle l'erreur
        if(!$post[0]) {
            $post = [null];
        }
		
        $commentForm = $this->createForm(CommentType::class);
	
		
        return $this->render('forum/index.html.twig', [
            'post' => $post[0],
            'user' => $this->getUser(),
            'commentForm' => $commentForm->createView()
		
        ]);
    }
	
	
	
	//Ecrire un post
	 #[Route('/forum/post/add', name: 'app_forumadd')]
	public function addPost(Request $request, EntityManagerInterface $entityManager): Response
    {
        $post = new Posts();
        $post->setCreated_Id($this->getUser());

        $postForm = $this->createForm(PostType::class, $post);
        $postForm->handleRequest($request);

        if ($postForm->isSubmitted() && $postForm->isValid()) {
            $entityManager->persist($post);
            $entityManager->flush();
        }
		
         return $this->redirectToRoute('app_forum');
    }
	
	
	//Ecrire un commentaire
    #[Route("/forum/{id}/comment/add", name: "add_comment")]
    public function addComment(Request $request, EntityManagerInterface $entityManager, Posts $post): Response
    {
        $comment = new Comments();
        $comment->setUserId($this->getUser());
        $comment->setPostId($post);

        $commentForm = $this->createForm(CommentType::class, $comment);
        $commentForm->handleRequest($request);

        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $entityManager->persist($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_forumpost', [
            'id' => $post->getId()
        ]);
    }
	
	#[Route('/forum', name: 'app_forum')]
    public function indexArticle(EntityManagerInterface $entityManager): Response
    {
        $posts = $entityManager->getRepository(Posts::class)->findAll();
		$postForm = $this->createForm(PostType::class);
        return $this->render('forum/forum.html.twig', [
            'posts' => $posts,
            'user' => $this->getUser(),
			'PostForm'=> $postForm->createView()
        ]);
    }
}

templates/forum/forum.html.twig
{% extends 'base.html.twig' %}

{% block title %}EcoGaming Forum{% endblock %}

{% block body %}


<div class="forum">
    <div class="card text-center w-100 mt-4 p-0 mb-4">
        <div class="card-header">Ecrire un post</div>
            <div class="card-body">
            {% if user %}
                {{ form_start(PostForm, {'action': path('app_forumadd')}) }}
                <button type="submit">Envoyer</button>
                {{ form_end(PostForm) }}
            {% else %}
                <h6 class="card-title text-muted">Tu dois être connecté(e) pour ça!</h6>
            {% endif %}
            </div>
        </div>
				

    {% if posts is empty %}
        <div class="forumempty"> <h1>Aucun post n'a été trouvé.</h1></div>
    {% else %}

        <h1>Forum</h1>
        <div class="list-group">

            {% for post in posts %}
                <a href="{{ path('app_forumpost', {'id':post.id})}}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ post.name }}</h5>
                        <small>Publié par {{ post.created_id.name }} le  {{post.datePublication|date('d/m/Y')}}</small>
                    </div>
                    <p class="mb-1">{{ post.description }}</p>
                </a>
            {% endfor %}


        </div>





    <div class="forumcontent">

        <div class="foruminfo">

		</div>
    </div>

    {% endif %}
</div>
{% endblock %}

templates/forum/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}EcoGaming Forum{% endblock %}


{% block body %}
    <div class="post">
    {% if post is empty %}
    <div class="nopost"> <p>Post non existant.</p></div>
    {% else %}
	<div class="postcontent">
        <h1>{{ post.name }}</h1>
        <h6>{{ post.description }}</h6>
        <p>{{ post.content }}</p>
        {# <h2>Créé par {{ post.created_id.name }} le </h2> #}
    </div>
	
        <div class="Réponses">Réponses <h1>({{ post.comments.count }})</h1></div>
                    {% for comment in post.comments %}
                        <h2>{{ comment.text }}</h2>{# <h3> de {{ comment.user.name }}</h3> #}
                    {% endfor %}
        </div>
</div>


                <div class="card text-center w-100 mt-4 p-0 mb-4">
                    <div class="card-header">Repondre</div>
                    <div class="card-body">
                    {% if user %}
                        {{ form_start(commentForm, {'action': path('add_comment', {'id': post.id})}) }}
                            {{ form_widget(commentForm.text) }}
                            <button type="submit">Envoyer</button>
                        {{ form_end(commentForm) }}
                    {% else %}
                        <h6 class="card-title text-muted">Tu dois être connecté(e) pour ça!</h6>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}